feature: добавил контроллер для запросов
yamax2/rubrics pull request #13
Opened 2017-07-12 10:27 UTC by pchellovod

https://jira.railsc.ru/browse/SERVICES-1904

2017-07-17 07:51 UTC, yamax2 requested changes

2017-07-17 07:51 UTC, yamax2 commented on app/controllers/requests_controller.rb
> +    @request = Request.new
тут давай сделаем `@client.requests.new`

2017-07-17 07:51 UTC, yamax2 commented on app/views/clients/index.haml
> +        %td= link_to client.name, client_url(client.id)
не `_url`, а `_path`

2017-07-17 07:51 UTC, yamax2 commented on app/views/requests/show.haml
> +  -#%td= link_to 'Destroy', [@client, @request], method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger'
это чего закоменчено?

2017-07-17 08:01 UTC, pchellovod commented on app/views/requests/show.haml
> +  -#%td= link_to 'Destroy', [@client, @request], method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger'
забыл раскоментить

2017-07-17 13:47 UTC, yamax2 requested changes

2017-07-17 13:47 UTC, yamax2 commented on spec/factories/request.rb
> +  factory :invalid_request do
давай не будет отдельную фабрику на неправильные данные, лучше так:
```
let(:req) { create :request, tile: nil, ...  }  
```

2017-07-17 13:47 UTC, yamax2 commented on spec/factories/request.rb
> +  # factory :req do
это чево?

2017-07-17 13:47 UTC, yamax2 commented on spec/controllers/requests_controller_spec.rb
> +    before { request }
тут наоборот:
```
let(:request) { delete ... }
```

а в `it`: `expect { request }.to ...`

2017-07-17 13:47 UTC, yamax2 commented on spec/controllers/requests_controller_spec.rb
> +      let(:request) { post :update,  params: {id: request.id, request: attributes_for(:request, title: nil, client: client) } }
тут не `client: client`, а `client_id: client.id` - ты же как-бы из браузера передаешь

2017-07-18 04:52 UTC, yamax2 requested changes

2017-07-18 04:52 UTC, yamax2 commented on spec/controllers/requests_controller_spec.rb
> +  let(:req) { create(:request, client: client) }
а вот это тут зачем?

2017-07-18 04:52 UTC, yamax2 commented on spec/controllers/requests_controller_spec.rb
> +    let(:request) { post :create, params: { client_id: client, request: req_attributes} }
`client_id: client` - что тут не так

2017-07-18 04:52 UTC, yamax2 commented on spec/controllers/requests_controller_spec.rb
> +        post :create, params: { client_id: client, request: attributes_for(:request) }
давай все в одном it для context

2017-07-18 04:52 UTC, yamax2 commented on spec/controllers/requests_controller_spec.rb
> +        expect { request }.to_not change(Request, :count)
давай еще проверим что ошибки не пустые и содержат title

2017-07-18 04:52 UTC, yamax2 commented on spec/controllers/requests_controller_spec.rb
> +    let(:del_request) { delete :destroy, params: { client_id: client, request: attributes_for(:request)} }
тут не нужны аттрибуты модели, мы же только удаляем - достаточно id реквеста

2017-07-18 06:44 UTC, yamax2 commented on spec/controllers/requests_controller_spec.rb
> -    let(:del_request) { delete :destroy, params: { client_id: client, request: attributes_for(:request)} }
а чево убрал? хорошо было с `del_request` - в expect всю эту колбасу читать сложно

2017-07-18 06:54 UTC, yamax2 commented on spec/controllers/requests_controller_spec.rb
> -    let(:del_request) { delete :destroy, params: { client_id: client, request: attributes_for(:request)} }
и тут еще в params пробелы лишние

2017-07-18 07:44 UTC, yamax2 commented on spec/controllers/requests_controller_spec.rb
> +
лишние строки

2017-07-18 07:44 UTC, yamax2 commented on spec/controllers/requests_controller_spec.rb
> +      before { request.validate }
это не нужно

2017-07-18 07:45 UTC, yamax2 commented on spec/controllers/requests_controller_spec.rb
> +      let(:request) { build :request, client_id: client, title: nil, body: nil }
тут нужен не build, а запрос через контроллер

2017-07-18 07:45 UTC, yamax2 commented on spec/controllers/requests_controller_spec.rb
> +
лишние строки

2017-07-18 08:05 UTC, yamax2 requested changes

2017-07-18 08:05 UTC, yamax2 commented on spec/controllers/requests_controller_spec.rb
> +      let(:request) { build :request, client_id: client, title: nil, body: nil }
уже есть же выше, надо просто `req_attributes` переопределить и опять `client_id: client`

2017-07-18 08:05 UTC, yamax2 commented on spec/controllers/requests_controller_spec.rb
> +        expect(request.errors).to_not be_empty
давай еще проверим что конкретные поля есть в ошибках

2017-07-18 08:05 UTC, yamax2 commented on spec/controllers/requests_controller_spec.rb
> +      expect { del_request }.to change(Request, :count).by(-1)
давай еще проверим что в переменной `@request` у нас правильный инстанс request и что редиректит куда надо

2017-07-18 08:56 UTC, yamax2 requested changes

2017-07-18 08:56 UTC, yamax2 commented on spec/controllers/requests_controller_spec.rb
> +        expect(assigns(:request).errors)
`.not_to be_empty`

2017-07-18 08:56 UTC, yamax2 commented on spec/controllers/requests_controller_spec.rb
> +
лишние строки ) и нет тестов `#update`

2017-07-18 10:44 UTC, yamax2 commented on spec/controllers/requests_controller_spec.rb
> +      let(:change) { post :update,  params: {client_id: client.id, id: request.id, request: attributes_for(:request, title: 'change_title')} }
:+1:

2017-07-18 10:45 UTC, yamax2 commented on spec/controllers/requests_controller_spec.rb
> +        request.reload
это можно не делать, т.к. ничего проверять не будем в нем

2017-07-18 10:57 UTC, yamax2 commented on app/controllers/requests_controller.rb
> +    params.require(:request).permit(:title, :body, :client_id)
а вот `client_id` тут не должен быть - он из параметров урла берется

2017-07-18 11:36 UTC, yamax2 approved these changes

2017-07-18 11:38 UTC, merged