feature: добавил контроллер и вьюхи для рубрик
yamax2/rubrics pull request #15
Opened 2017-07-20 07:27 UTC by pchellovod

https://jira.railsc.ru/browse/SERVICES-1904

2017-07-20 07:32 UTC, KirillFurtikov commented on app/views/rubrics/show.haml
> += link_to 'New Request', new_rubric_path, class: 'btn btn-warning'
New Rubric

2017-07-20 07:32 UTC, KirillFurtikov commented on app/views/rubrics/index.haml
> +        %td= link_to 'Edit', edit_rubric_path(rubric), class: 'btn btn-info'
В чем отличие от предыдущей линки?) адрес одинаковый

2017-07-20 07:32 UTC, KirillFurtikov commented on app/views/layouts/application.haml
> +          %a.navbar-brand{href: '/'} Main
может весь navbar вынести в _top_menu.haml и рендерить уже тут?

2017-07-20 07:33 UTC, yamax2 requested changes

2017-07-20 07:33 UTC, yamax2 commented on app/views/layouts/application.haml
> +              %a{href: 'rubrics'} Rubrics
давай это и ниже через `link_to`

2017-07-20 07:33 UTC, yamax2 commented on app/views/layouts/application.haml
> +          %a.navbar-brand{href: '/'} Main
`link_to`

2017-07-20 07:33 UTC, yamax2 commented on app/controllers/rubrics_controller.rb
> +      @rubrics = Rubric.where(rubric_id: nil)
давай для этого сделаем отдельный scope в модели

2017-07-20 07:57 UTC, KirillFurtikov commented on app/views/pages/index.haml
> += link_to 'Errors', class: 'btn btn-primary'
а path-то какой?

2017-07-20 07:59 UTC, pchellovod commented on app/views/pages/index.haml
> += link_to 'Errors', class: 'btn btn-primary'
пока никакого

2017-07-20 07:59 UTC, KirillFurtikov commented on app/views/layouts/application.haml
>              %li.active
у Rubrics получается, что всегда будет active, а должно быть у того, в котором находимся

2017-07-20 08:01 UTC, yamax2 commented on app/views/layouts/application.haml
>              %li.active
давайте эти моменты отдельно ) после принятия рубрик проведем приборку во вьюхах, сделаем хлебные крошки

2017-07-20 12:11 UTC, yamax2 commented
надо тесты для контроллера добавить

2017-07-21 07:29 UTC, yamax2 requested changes

2017-07-21 07:29 UTC, yamax2 commented on app/views/layouts/_top_menu.haml
> +        %li{:class => "#{'active' if current_page?(root_path)}"}=link_to 'Main', root_path
давай это покороче запишем: `class: params[:controller] == 'pages' ? 'active'  : ''`
могу ошибаться в переменной `controller` - надо загуглить

2017-07-21 07:29 UTC, yamax2 commented on app/views/layouts/_top_menu.haml
> +        %li{href: '#about'} About
а это что ? )

2017-07-21 07:29 UTC, yamax2 commented on app/views/rubrics/index.haml
> +        %td= link_to 'Destroy', rubric, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-warning'
`{ confirm: 'Are you sure?' }` - пробелы

2017-07-24 07:18 UTC, yamax2 commented
все норм, можно делать rebase, только замечания пофиксить и пробелы

2017-07-24 09:16 UTC, yamax2 approved these changes
:+1:  давай rebase

2017-07-24 09:32 UTC, merged