feature: добавил breadcrumbs для клиентов/запросов
yamax2/rubrics pull request #16
Opened 2017-07-24 12:50 UTC by pchellovod

https://jira.railsc.ru/browse/SERVICES-1904

2017-07-24 12:54 UTC, yamax2 requested changes

2017-07-24 12:54 UTC, yamax2 commented on Gemfile
> +  gem 'gretel', '~> 3.0.9'
а чего его только в dev и test? его везде надо

2017-07-24 12:54 UTC, yamax2 commented on config/breadcrumbs/rubrics.rb
> +# crumb :rubrics do |rubric|
давай все лишнее (комменты) поубираем

2017-07-25 07:10 UTC, yamax2 approved these changes
небольшая правка и принимаем

2017-07-25 07:10 UTC, yamax2 commented on app/views/rubrics/index.haml
> +- if @rubric.nil?
`if @rubric`

2017-07-25 07:19 UTC, merged

2017-07-25 07:27 UTC, KirillFurtikov commented
Юзай https://github.com/bbatsov/rubocop для проверки чистоты кода, а то наблюдаю кучу пустых строк в некоторых файлах

2017-07-25 07:28 UTC, yamax2 commented
че-т я пропустил пустые строки