fix: добавил пагинацию для рубрик, пользователей и запросов, добавил рубрикам контент
yamax2/rubrics pull request #18
Opened 2017-07-25 09:29 UTC by pchellovod

https://jira.railsc.ru/browse/SERVICES-1904

2017-07-25 09:33 UTC, KirillFurtikov commented on app/views/rubrics/edit.haml
> +    %br/
Уже давно хотел написать. Может не костылить br'ами, а в div'ы заворачивать?

2017-07-25 09:33 UTC, yamax2 requested changes
а можешь еще скрин приложить

2017-07-25 09:33 UTC, yamax2 commented on app/views/kaminari/.directory
> +[Dolphin]
а это хто? )

2017-07-25 09:33 UTC, yamax2 commented on app/views/kaminari/_last_page.html.haml
> +  = link_to_unless current_page.last?, raw(t 'views.pagination.last'), url, {:remote => remote}
ракеты надо убрать

2017-07-25 09:33 UTC, yamax2 commented on app/views/kaminari/_first_page.html.haml
> +  = link_to_unless current_page.first?, raw(t 'views.pagination.first'), url, :remote => remote
ракеты

2017-07-25 09:33 UTC, yamax2 commented on app/models/rubric.rb
> +  max_paginates_per 10
помоему тут надо выставлять параметр `default_per_page`

2017-07-25 09:34 UTC, yamax2 commented
еще тесты упали

2017-07-25 10:00 UTC, KirillFurtikov commented on app/views/rubrics/edit.haml
> +    = f.text_field :content
А что за content? Это описание тематики рубрики или что? Вижу, что валидации нет, соответственно поле может иметь огромное количество-символов. Может быть тогда перевести в **_text_area_** его?

2017-07-25 10:01 UTC, yamax2 commented on app/views/rubrics/edit.haml
> +    %br/
поддерживаю, надо вообще формы привести к нормальному виду на [bootstrap](http://getbootstrap.com/css/#forms), только лучше отдельным реквестом

2017-07-25 10:02 UTC, yamax2 commented on app/views/rubrics/edit.haml
> +    = f.text_field :content
да, его надо через `textarea`. я че-т не помню что мы имели ввиду когда добавляли его

2017-07-25 10:03 UTC, yamax2 commented
коммит бы еще переименовать попроще типа `feature: пагинация сущностей`

2017-07-25 10:46 UTC, pchellovod commented on app/views/kaminari/.directory
> +[Dolphin]
дельфин какой-то

2017-07-25 10:46 UTC, pchellovod commented on app/views/rubrics/edit.haml
> +    %br/
попробую

2017-07-25 10:47 UTC, yamax2 commented on app/views/kaminari/.directory
> +[Dolphin]
давай уберем - в `.gitignore` его

2017-07-25 11:21 UTC, KirillFurtikov commented on app/views/kaminari/_first_page.html.haml
> +  = link_to_unless current_page.first?, raw(t 'views.pagination.first'), url, remote:remote
пробела между ключом и значением не хватает

2017-07-25 11:22 UTC, KirillFurtikov commented on app/views/kaminari/_first_page.html.haml
> +  = link_to_unless current_page.first?, raw(t 'views.pagination.first'), url, remote:remote
@yamax2 нормальная практика, когда ключ и значение имеют одинаковое название? Может из как-то по-разному называть?

2017-07-25 11:23 UTC, yamax2 commented
чорд, надо же еще тесты сделать для пагинации - что контроллеры отдают столько сколько нужно в `index`

2017-07-25 11:24 UTC, yamax2 commented on app/views/kaminari/_first_page.html.haml
> +  = link_to_unless current_page.first?, raw(t 'views.pagination.first'), url, remote:remote
норм, `remote` это же переменная партиала, наоборот наглядно получается

2017-07-25 11:24 UTC, KirillFurtikov commented
не уверен, но мне кажется лучше переименовать `app/views/kaminari` в что-то более понятное, например: `app/views/pagination`

2017-07-25 11:24 UTC, yamax2 commented
![image](https://user-images.githubusercontent.com/7448667/28570052-c8a265a2-7155-11e7-9a98-abc5793f3fc5.png)

2017-07-25 11:26 UTC, yamax2 commented
> лучше переименовать app/views/kaminari

да, можно заморочиться - почитать доки придется, с перепоя можно легко забыть что такое `kaminari`

2017-07-25 11:37 UTC, yamax2 commented
лол )) https://test.mytm.tk/rubrics?rubric_id=566

2017-07-26 05:08 UTC, yamax2 requested changes

2017-07-26 05:08 UTC, yamax2 commented on app/views/pagination/kaminari/_next_page.html.haml
> +  = link_to_unless current_page.last?, raw(t 'views.pagination.next'), url, :rel => 'next', :remote => remote
ракеты остались, надо везде проверить

2017-07-26 05:08 UTC, yamax2 commented on spec/controllers/clients_controller_spec.rb
> +        expect(assigns(:clients)).to_not match_array(clients)
а давай прям количество проверим когда page = 1 и когда page = 2

2017-07-26 07:34 UTC, yamax2 approved these changes

2017-07-26 07:35 UTC, KirillFurtikov approved these changes

2017-07-26 07:41 UTC, merged