feature: rubrics views
yamax2/rubrics pull request #23
Opened 2017-07-31 11:28 UTC by KirillFurtikov

Решает: https://github.com/yamax2/rubrics/issues/21
Разделить на два ПР можно даже, наверное. Второй потом зашлю, как допилю. 
Посмотреть можно здесь: http://10.101.100.105:3000/rubrics

2017-07-31 11:37 UTC, yamax2 commented
а хто такой  https://github.com/useername ?

2017-07-31 11:38 UTC, KirillFurtikov commented
пофиксил, косяк с кодировкой был)

2017-07-31 11:39 UTC, yamax2 commented
тут бы автофокус навесить на title:
![image](https://user-images.githubusercontent.com/7448667/28776159-db63e202-760e-11e7-85cf-62c3410dea1b.png)

2017-07-31 11:47 UTC, yamax2 requested changes

2017-07-31 11:47 UTC, yamax2 commented on app/views/clients/edit.haml
> += link_to '', :back, class: 'btn btn-outline-primary glyphicon glyphicon-chevron-left'
`:back` думаю не очень гут, может на индекс тупо ссылку сделать?

2017-07-31 11:47 UTC, yamax2 commented on app/views/clients/edit.haml
> +  %h1 Editing Client
сюда бы хлебных крошек добавить тоже

2017-07-31 11:47 UTC, yamax2 commented on app/views/clients/index.haml
> +        = link_to '', new_client_path, class: 'btn btn-primary btn-sm glyphicon glyphicon-file', title: 'Create new client'
давай это будет `btn-success`, прост чтоб отличалось от редактирования

2017-07-31 11:47 UTC, yamax2 commented on app/views/layouts/_top_menu.haml
> +      %button.navbar-toggle.collapsed{'aria-controls' => 'navbar', 'aria-expanded' => 'false', 'data-target' => '#navbar', 'data-toggle' => 'collapse', type: 'button'}
:+1:

2017-07-31 11:47 UTC, yamax2 commented on app/views/layouts/_top_menu.haml
> +        %li{class: params[:controller] == 'rubrics' ? 'active' : ''}= link_to 'Rubrics', rubrics_path
:+1:

2017-07-31 11:47 UTC, yamax2 commented on app/views/rubrics/new.haml
> +        = f.text_field :title, class: 'form-control', :autofocus => true
ракета

2017-07-31 11:47 UTC, yamax2 commented on app/views/rubrics/show.haml
> +
пустая строка лишняя

2017-07-31 11:50 UTC, KirillFurtikov commented on app/views/clients/edit.haml
> += link_to '', :back, class: 'btn btn-outline-primary glyphicon glyphicon-chevron-left'
может тогда вообще выпилю? Есть navbar + эту форму можно в modal вынести потом, а там это явно не нужно

2017-07-31 11:50 UTC, yamax2 commented on app/views/clients/edit.haml
> += link_to '', :back, class: 'btn btn-outline-primary glyphicon glyphicon-chevron-left'
да, давай так

2017-08-01 08:21 UTC, KirillFurtikov commented on app/views/clients/edit.haml
> +  %h1 Editing Client
тоже в modal полетит, не нужно)

2017-08-01 08:22 UTC, yamax2 commented on app/views/clients/edit.haml
> +- breadcrumb :clients
что-то тут не так, надо для отдельного клиента крошку
а на остальных сущностях есть крошки для `edit` ?

2017-08-01 08:23 UTC, yamax2 commented on app/views/clients/edit.haml
> +  %h1 Editing Client
давай пока везде хотяб крошки понаставим

2017-08-01 08:24 UTC, KirillFurtikov commented on app/views/clients/edit.haml
> +- breadcrumb :clients
блин, вставлял, чтоб посмотреть как будет выглядеть, выпилить забыл вовсе)

2017-08-02 08:02 UTC, yamax2 requested changes

2017-08-02 08:02 UTC, yamax2 commented on config/breadcrumbs/clients.rb
> +crumb :new_client do
давай сделаем везде одинаково: хлебная крошка при редактировании и создании пусть будет такая же как на show

2017-08-02 08:17 UTC, yamax2 approved these changes

2017-08-02 08:19 UTC, yamax2 commented on config/breadcrumbs/clients.rb
> +  link client.name, client
еще косячок нашел 
![image](https://user-images.githubusercontent.com/7448667/28864159-10ca8e38-7785-11e7-976c-48d89b8ca425.png)

давай как-то так на всех сущностях
`client.name || "new #{client.model_name.human}"'

2017-08-02 08:20 UTC, yamax2 commented on app/views/clients/new.haml
> +- breadcrumb :clients
неправильная крошка

2017-08-02 08:50 UTC, KirillFurtikov commented on config/breadcrumbs/clients.rb
> +  link client.name || %Q(new #{client.model_name.human}).capitalize, client
В таком формате нормально?

2017-08-02 08:51 UTC, yamax2 commented on config/breadcrumbs/clients.rb
> +  link client.name || %Q(new #{client.model_name.human}).capitalize, client
да, пусть будет так

2017-08-02 08:52 UTC, yamax2 approved these changes

2017-08-02 08:58 UTC, merged