feature: добавил тесты на валидацию модели
yamax2/rubrics pull request #6
Opened 2017-06-26 09:31 UTC by pchellovod

https://jira.railsc.ru/browse/SERVICES-1904

2017-06-26 09:40 UTC, yamax2 requested changes
еще вот это можно почитать http://www.betterspecs.org/ru/

2017-06-26 09:40 UTC, yamax2 commented on Gemfile
> +  gem 'capybara'
а это для чего тут? )

2017-06-26 09:40 UTC, yamax2 commented on spec/models/rubric_spec.rb
> +    expect(Rubric.new(title: '123')).to be_valid
`Rubric.new(title: '123')` лучше сделать так
```
let(:rubric) { described_class.new(title: '123') } 
```

а лучше так 
```
subject { described_class.new(title: '123') } 
```

тогда можно будет писать так:
```
it { is_expected.to be_valid } 
```

а ваще самое правильное будет написать factories с помощью factory_girl 

вот [тут](https://github.com/yamax2/ykrop/blob/master/spec/models/target_urls/region_settings_spec.rb) можно порыться в примерах тестов для моделей

2017-06-26 09:47 UTC, pchellovod commented on Gemfile
> +  gem 'capybara'
для аццептанс тестов, которых ещё нет

2017-06-26 09:49 UTC, yamax2 commented on Gemfile
> +  gem 'capybara'
это про эмуляцию действий пользователя?

2017-06-29 09:28 UTC, pchellovod commented on Gemfile
> +  gem 'capybara'
да

2017-06-29 09:29 UTC, yamax2 commented on Gemfile
> +  gem 'capybara'
давай выпилим, такие тесты обычно тестер делает

2017-06-29 12:28 UTC, yamax2 requested changes

2017-06-29 12:28 UTC, yamax2 commented on spec/models/rubric_spec.rb
> +    it { should_not allow_value(" ").for(:title) }
а как такая валидация отрабатывает? вроде нигде нет удаления пробелов? или это я туплю )

2017-06-29 12:28 UTC, yamax2 commented on spec/models/rubric_spec.rb
> +    it { should validate_presence_of :title }
а давай так `is_expected.to validate_presence_of(:title)`  - возможно что-то еще придется подключить

2017-06-29 12:28 UTC, yamax2 commented on spec/models/rubric_spec.rb
>  RSpec.describe Rubric, type: :model do
`type` вроде можно не указывать сейчас

2017-06-29 12:44 UTC, yamax2 requested changes

2017-06-29 12:44 UTC, yamax2 commented on spec/models/rubric_spec.rb
> +
лишняя строка

2017-06-29 12:45 UTC, yamax2 commented
:+1:  то что надо, еще чуть:
* давай убедимся что при удалении рубрики удаляются все её подрубрики
* что нельзя создать рубрику с левым parent_id

2017-06-29 12:47 UTC, yamax2 commented
за пробелы кста можно заморочиться - подключить готовое решение типа [этого](https://github.com/rmm5t/strip_attributes)

2017-06-29 12:48 UTC, pchellovod commented on spec/models/rubric_spec.rb
> +    it { should_not allow_value(" ").for(:title) }
это я туплю, уберу её

2017-06-30 08:15 UTC, yamax2 requested changes
давай резделим валидации и работу с подрубриками - все что с подрубриками вынесем в отдельный блок `describe rubrics`, в т.ч. создание `let(...) ...`

2017-06-30 08:15 UTC, yamax2 commented on spec/models/rubric_spec.rb
> +
пустая строка

2017-06-30 08:15 UTC, yamax2 commented on spec/models/rubric_spec.rb
> +    it { expect(:title).not_to eq(' ') }
это что-то не то )

2017-06-30 08:18 UTC, yamax2 commented
проверить что удаляются пробелы можно как-то вот [так](https://github.com/yamax2/ykrop/blob/master/spec/models/template_spec.rb#L372)

2017-06-30 08:52 UTC, yamax2 requested changes
ну и остался тест с левым `parent_id`

2017-06-30 08:52 UTC, yamax2 commented on spec/models/rubric_spec.rb
> +      let(:rubric) { build :rubric, title: ' word1 word2 '}
попробуй тут сделать `create` вместо `build` - мне кажется тогда и `before` не потребуется

2017-06-30 08:52 UTC, yamax2 commented on spec/models/rubric_spec.rb
> +    context 'have repeated spaces' do
:+1:

2017-06-30 10:26 UTC, yamax2 commented on spec/models/rubric_spec.rb
> +    context 'when parent_is is wrong' do
очепятка `parent_id`

2017-06-30 10:28 UTC, yamax2 commented on spec/models/rubric_spec.rb
> +    context 'have repeated spaces' do
'when has whitespace` как-то так, контекст это когда что-то...

2017-06-30 10:53 UTC, yamax2 approved these changes

2017-06-30 11:25 UTC, merged